/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jan 9, 2012, 5:08:03 PM
 */
package com.kitfox.svg.test.gregorz;

import java.awt.BorderLayout;

/**
 *
 * @author kitfox
 */
public class NewJFrame extends javax.swing.JFrame
{
    TestPanel1 panel = new TestPanel1();

    /** Creates new form NewJFrame */
    public NewJFrame()
    {
        initComponents();

        getContentPane().add(panel, BorderLayout.CENTER);
        setSize(500, 500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
