/*
 * BeansSuite.java
 * JUnit based test
 *
 * Created on May 20, 2005, 4:34 AM
 */

package com.kitfox.svg.app.beans;

import junit.framework.*;

/**
 *
 * @author kitfox
 */
public class BeansSuite extends TestCase
{
    
    public BeansSuite(String testName)
    {
        super(testName);
    }

    protected void setUp() throws Exception
    {
    }

    protected void tearDown() throws Exception
    {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite()
    {
        TestSuite suite = new TestSuite("BeansSuite");
//        suite.addTest(com.kitfox.svg.app.beans.ProportionalLayoutPanelTest.suite());
        suite.addTest(com.kitfox.svg.app.beans.SVGIconTest.suite());
//        suite.addTest(com.kitfox.svg.app.beans.SVGPanelTest.suite());
        return suite;
    }
    
}
